/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasProjeto;
import javax.swing.JOptionPane;
import java.awt.Color;


/**
 *
 * @author FAETEC-PÁDUA
 */
public class ProjetoFinal extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoFinal
     */
    public ProjetoFinal() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MoneyControl Center");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 221, 230));
        setResizable(false);

        cadastroBTN.setFont(new java.awt.Font("Arial Black", 0, 14));
        cadastroBTN.setText("Cadastrar");
        cadastroBTN.setForeground(Color.BLUE); // Altera a cor do texto para azul

        loginBTN.setFont(new java.awt.Font("Arial Black", 0, 14));
        loginBTN.setText("Entrar");
        loginBTN.setForeground(Color.BLUE); // Altera a cor do texto para azul

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        presentLABEL = new javax.swing.JLabel();
        cadastroBTN = new javax.swing.JButton();
        loginBTN = new javax.swing.JButton();
        sobreBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MoneyControl Center");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 221, 230));
        setResizable(false);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        getContentPane().setLayout(layout);

        presentLABEL.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        presentLABEL.setText("Money Control Center");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 37, 0, 0);
        getContentPane().add(presentLABEL, gridBagConstraints);

        cadastroBTN.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cadastroBTN.setText("Cadastrar");
        cadastroBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroBTNActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(94, 31, 0, 0);
        getContentPane().add(cadastroBTN, gridBagConstraints);

        loginBTN.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        loginBTN.setText("Entrar");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(94, 23, 0, 43);
        getContentPane().add(loginBTN, gridBagConstraints);

        sobreBTN.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        sobreBTN.setText("Sobre");
        sobreBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreBTNActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(121, 0, 0, 0);
        getContentPane().add(sobreBTN, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void cadastroBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroBTNActionPerformed
        LoginTela newFrame = new LoginTela ();
        newFrame.setVisible(true);
    }//GEN-LAST:event_cadastroBTNActionPerformed

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        // TODO add your handling code here:
        CadastroTela newframe = new CadastroTela ();
        newframe.setVisible(true);
    }//GEN-LAST:event_loginBTNActionPerformed

    private void sobreBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreBTNActionPerformed
        String mensagem = "Esse é um software de controle financeiro para o Projeto Final do Curso Técnico em Informática da Faetec - Sto Antonio de Padua.";
        JOptionPane.showMessageDialog(this, mensagem, "Sobre", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_sobreBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroBTN;
    private javax.swing.JButton loginBTN;
    private javax.swing.JLabel presentLABEL;
    private javax.swing.JButton sobreBTN;
    // End of variables declaration//GEN-END:variables
}
