/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import javax.swing.JPanel;
import java.awt.Color;

/**
 *
 * @author reydemonio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        int screenWidth = 865;
        int screenHeight = 516;
        
        
        // adicionar o JPanel
        JPanel panel = new JPanel();
        panel.setBackground(new Color(0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informativoLABEL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        painelLINHA = new javax.swing.JPanel();
        circulanteATV = new javax.swing.JLabel();
        nomecontaATVLABEL = new javax.swing.JLabel();
        nomeCONTATXT = new javax.swing.JTextField();
        opcaoUMATVBTN = new javax.swing.JRadioButton();
        naocirculanteATV = new javax.swing.JLabel();
        opcaoDOISATVBTN = new javax.swing.JRadioButton();
        valorcontaATVLABEL = new javax.swing.JLabel();
        valorcontaTXT = new javax.swing.JTextField();
        circulantePASS = new javax.swing.JLabel();
        naocirculantePASS = new javax.swing.JLabel();
        opcaoUMPASSBTN = new javax.swing.JRadioButton();
        opcaoDOISPASSBTN = new javax.swing.JRadioButton();
        nomecontaPASSLABEL = new javax.swing.JLabel();
        nomecontaPASSTXT = new javax.swing.JTextField();
        valorcontaPASSLABEL = new javax.swing.JLabel();
        valorcontaPASSTXT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        patrimonioLABEL1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patrimonioLIQUIDOTXT = new javax.swing.JTextArea();
        voltarBTN = new javax.swing.JButton();
        calculoBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        informativoLABEL.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        informativoLABEL.setText("Insira os dados abaixo para calcular o Balanço Patrimonial da Empresa:");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Ativos");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Passivos");

        painelLINHA.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout painelLINHALayout = new javax.swing.GroupLayout(painelLINHA);
        painelLINHA.setLayout(painelLINHALayout);
        painelLINHALayout.setHorizontalGroup(
            painelLINHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        painelLINHALayout.setVerticalGroup(
            painelLINHALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        circulanteATV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        circulanteATV.setText("Circulante");

        nomecontaATVLABEL.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomecontaATVLABEL.setText("Nome:");

        nomeCONTATXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCONTATXTActionPerformed(evt);
            }
        });

        naocirculanteATV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        naocirculanteATV.setText("Não Circulante");

        valorcontaATVLABEL.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        valorcontaATVLABEL.setText("Valor:");

        circulantePASS.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        circulantePASS.setText("Circulante");

        naocirculantePASS.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        naocirculantePASS.setText("Não Circulante");

        nomecontaPASSLABEL.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nomecontaPASSLABEL.setText("Nome:");

        valorcontaPASSLABEL.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        valorcontaPASSLABEL.setText("Valor:");

        jButton1.setText("+");

        jButton2.setText("+");

        patrimonioLABEL1.setText("Patrimônio Liquído: ");

        patrimonioLIQUIDOTXT.setEditable(false);
        patrimonioLIQUIDOTXT.setColumns(20);
        patrimonioLIQUIDOTXT.setRows(5);
        jScrollPane1.setViewportView(patrimonioLIQUIDOTXT);

        voltarBTN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        voltarBTN.setText("Voltar");

        calculoBTN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        calculoBTN.setText("Calcular");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(circulanteATV)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(opcaoUMATVBTN)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(opcaoDOISATVBTN)
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(naocirculanteATV)
                                .addGap(42, 42, 42))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valorcontaATVLABEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valorcontaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(nomecontaATVLABEL)
                                .addGap(18, 18, 18)
                                .addComponent(nomeCONTATXT, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(painelLINHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(circulantePASS)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(opcaoDOISPASSBTN)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomecontaPASSLABEL)
                                        .addComponent(valorcontaPASSLABEL)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomecontaPASSTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(valorcontaPASSTXT))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(naocirculantePASS)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(opcaoUMPASSBTN))
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jButton2)
                .addGap(312, 312, 312)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patrimonioLABEL1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(voltarBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calculoBTN))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(informativoLABEL)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(informativoLABEL)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(circulanteATV)
                                        .addGap(7, 7, 7)
                                        .addComponent(opcaoUMATVBTN)
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nomecontaATVLABEL)
                                            .addComponent(nomeCONTATXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(naocirculantePASS)
                                            .addComponent(circulantePASS))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(opcaoDOISPASSBTN)
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(nomecontaPASSLABEL)
                                                    .addComponent(nomecontaPASSTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(opcaoUMPASSBTN))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(valorcontaPASSLABEL)
                                            .addComponent(valorcontaPASSTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(naocirculanteATV)
                                        .addGap(18, 18, 18)
                                        .addComponent(opcaoDOISATVBTN)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(valorcontaATVLABEL)
                                    .addComponent(valorcontaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)))
                        .addComponent(patrimonioLABEL1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(painelLINHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarBTN)
                    .addComponent(calculoBTN)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCONTATXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCONTATXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCONTATXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculoBTN;
    private javax.swing.JLabel circulanteATV;
    private javax.swing.JLabel circulantePASS;
    private javax.swing.JLabel informativoLABEL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel naocirculanteATV;
    private javax.swing.JLabel naocirculantePASS;
    private javax.swing.JTextField nomeCONTATXT;
    private javax.swing.JLabel nomecontaATVLABEL;
    private javax.swing.JLabel nomecontaPASSLABEL;
    private javax.swing.JTextField nomecontaPASSTXT;
    private javax.swing.JRadioButton opcaoDOISATVBTN;
    private javax.swing.JRadioButton opcaoDOISPASSBTN;
    private javax.swing.JRadioButton opcaoUMATVBTN;
    private javax.swing.JRadioButton opcaoUMPASSBTN;
    private javax.swing.JPanel painelLINHA;
    private javax.swing.JLabel patrimonioLABEL1;
    private javax.swing.JTextArea patrimonioLIQUIDOTXT;
    private javax.swing.JLabel valorcontaATVLABEL;
    private javax.swing.JLabel valorcontaPASSLABEL;
    private javax.swing.JTextField valorcontaPASSTXT;
    private javax.swing.JTextField valorcontaTXT;
    private javax.swing.JButton voltarBTN;
    // End of variables declaration//GEN-END:variables
}
